project:
  type: website
  output-dir: docs
website:
  navbar:
    pinned: true
    logo: "/images/about_us.png"
    left:
      - about.qmd
      - href: statistics/index.qmd
        text: Statistics
      - href: machinelearning/index.qmd
        text: Machine Learning
      - href: deeplearning/index.qmd
        text: Deep Learning
      - href: nlp/index.qmd
        text: NLP
      - href: genai/index.qmd
        text: Gen AI

format:
  html:
    page-layout: full
    theme: [zephyr,theme.scss]
    css: styles.css
    toc: true



